version: "3.3"

services:
  web:
    container_name: cserkweb_django
    build: ./
    command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn --workers=3 cserkweb.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    expose:
      - 8000
    env_file:
      - .env
    restart: always # Lehet hogy a web hamarabb indul el, mint az adatbázis
    depends_on:
      - db

  db:
    container_name: cserkweb_postgres
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  nginx:
    container_name: cserkweb_nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static:
  media:
