version: "3.7"

services:
  web:
    container_name: cserkweb_django
    build: ./
    image: pmisi/cserkweb_web
    command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn --workers=3 cserkweb.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    expose:
      - 8000
    env_file:
      - .env
    restart: always # Lehet hogy a web hamarabb indul el, mint az adatbázis
    depends_on:
      - db
      
  db:
    container_name: cserkweb_postgres
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  nginx:
    container_name: cserkweb_nginx
    build: ./nginx
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    ports:
      - 80:80
    depends_on:
      - web

  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: watchtower cserkweb_django --interval 30
    restart: unless-stopped

volumes:
  postgres_data:
  static:
  media: