version: "3.3"

# Github actions besokkal (Out of memory), ha egyszerre kell futtatnia a djangot, nginx-et és a postres-t
# Ezért használjuk ezt a docker-compose fájlt, hogy csak helyi sqlite adatbázist futtassunk

services:
  web:
    container_name: cserkweb_django_ci
    build: ./
    command: python manage.py runserver
    volumes:
      - ./:/usr/src/app/
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    env_file:
      - .env.ci

volumes:
  static:
  media:
