# Generated by Django 3.0b1 on 2019-10-20 12:18

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bejegyzes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Cím')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Szöveg')),
                ('image', models.ImageField(upload_to='blog/cover_images/', verbose_name='Borítókép')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozás')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Utolsó módosítás')),
                ('slug', models.SlugField(unique=True, verbose_name='Link cím')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Író')),
            ],
            options={
                'verbose_name': 'Bejegyzés',
                'verbose_name_plural': 'Bejegyzések',
            },
        ),
    ]
