# Generated by Django 3.0b1 on 2019-11-09 19:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Post')),
                ('published', models.BooleanField(default=True, verbose_name='Közzétett állapot')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kezdeti dátum és idő')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Befejezési dátum és idő')),
            ],
            options={
                'verbose_name': 'Esemény',
                'verbose_name_plural': 'Események',
            },
            bases=('blog.post',),
        ),
    ]
