# Generated by Django 3.0a1 on 2019-10-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bejegyzes',
            name='slug',
            field=models.SlugField(default='dfd-df', unique=True),
            preserve_default=False,
        ),
    ]
