# Generated by Django 3.0b1 on 2019-10-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog/cover_images/', verbose_name='Borítókép'),
        ),
    ]
