# Generated by Django 3.0a1 on 2019-10-13 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_bejegyzes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bejegyzes',
            name='author',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Író'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bejegyzes',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Link cím'),
        ),
    ]
