# Generated by Django 3.0a1 on 2019-10-13 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20191013_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bejegyzes',
            name='author',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Író'),
            preserve_default=False,
        ),
    ]
