# Generated by Django 3.0b1 on 2019-10-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191013_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='bejegyzes',
            name='image',
            field=models.ImageField(default=None, upload_to='cover_images/', verbose_name='Borítókép'),
            preserve_default=False,
        ),
    ]
