# Generated by Django 3.0b1 on 2019-10-18 14:56

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_bejegyzes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bejegyzes',
            name='image',
            field=models.ImageField(upload_to='blog/cover_images/', verbose_name='Borítókép'),
        ),
        migrations.AlterField(
            model_name='bejegyzes',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Szöveg'),
        ),
    ]
